export const goods = [
  {
    name: "Cucumbers",
    type: "vegetables",
    price_per_kg: 15.0,
    kg_in_stock: 30,
    color: "green",
    origin_country: "Poland",
  },
  {
    name: "Apples",
    type: "fruits",
    price_per_kg: 18.8,
    kg_in_stock: 40,
    color: "red",
    origin_country: "Ukraine",
  },
  {
    name: "Potatoes",
    type: "vegetables",
    price_per_kg: 8.5,
    kg_in_stock: 60,
    color: "brown",
    origin_country: "Ukraine",
  },
  {
    name: "Bananas",
    type: "fruits",
    price_per_kg: 32.0,
    kg_in_stock: 25,
    color: "yellow",
    origin_country: "Ecuador",
  },
  {
    name: "Onions",
    type: "vegetables",
    price_per_kg: 5.0,
    kg_in_stock: 45,
    color: "white",
    origin_country: "Ukraine",
  },
  {
    name: "Oranges",
    type: "fruits",
    price_per_kg: 22.3,
    kg_in_stock: 35,
    color: "orange",
    origin_country: "Spain",
  },
  {
    name: "Carrots",
    type: "vegetables",
    price_per_kg: 9.2,
    kg_in_stock: 55,
    color: "orange",
    origin_country: "Ukraine",
  },
  {
    name: "Pears",
    type: "fruits",
    price_per_kg: 20.1,
    kg_in_stock: 28,
    color: "yellow",
    origin_country: "Ukraine",
  },
  {
    name: "Broccoli",
    type: "vegetables",
    price_per_kg: 12.5,
    kg_in_stock: 20,
    color: "green",
    origin_country: "Poland",
  },
  {
    name: "Melons",
    type: "fruits",
    price_per_kg: 28.7,
    kg_in_stock: 18,
    color: "green",
    origin_country: "Turkey",
  },
  {
    name: "Tomatoes",
    type: "vegetables",
    price_per_kg: 14.3,
    kg_in_stock: 42,
    color: "red",
    origin_country: "Ukraine",
  },

  {
    name: "Asparagus",
    type: "vegetables",
    price_per_kg: 18.0,
    kg_in_stock: 15,
    color: "green",
    origin_country: "Mexico",
  },
  {
    name: "Mangoes",
    type: "fruits",
    price_per_kg: 25.6,
    kg_in_stock: 32,
    color: "yellow",
    origin_country: "India",
  },
  {
    name: "Lettuce",
    type: "greens",
    price_per_kg: 6.8,
    kg_in_stock: 38,
    color: "green",
    origin_country: "Ukraine",
  },
  {
    name: "Peaches",
    type: "fruits",
    price_per_kg: 23.4,
    kg_in_stock: 26,
    color: "red",
    origin_country: "Spain",
  },
  {
    name: "Peas",
    type: "vegetables",
    price_per_kg: 11.2,
    kg_in_stock: 48,
    color: "green",
    origin_country: "Ukraine",
  },
  {
    name: "Avocado",
    type: "fruits",
    price_per_kg: 34.9,
    kg_in_stock: 24,
    color: "green",
    origin_country: "Mexico",
  },
  {
    name: "Cabbage",
    type: "vegetables",
    price_per_kg: 7.5,
    kg_in_stock: 36,
    color: "white",
    origin_country: "Ukraine",
  },
  {
    name: "Pumpkin",
    type: "vegetables",
    price_per_kg: 7.3,
    kg_in_stock: 86,
    color: "white",
    origin_country: "Ukraine",
  },
  {
    name: "Spinach",
    type: "greens",
    price_per_kg: 9.7,
    kg_in_stock: 18,
    color: "green",
    origin_country: "USA",
  },
  {
    name: "Strawberries",
    type: "fruits",
    price_per_kg: 40.5,
    kg_in_stock: 15,
    color: "red",
    origin_country: "Mexico",
  },
  {
    name: "Zucchini",
    type: "vegetables",
    price_per_kg: 14.8,
    kg_in_stock: 25,
    color: "green",
    origin_country: "Italy",
  },
  {
    name: "Cherries",
    type: "fruits",
    price_per_kg: 35.2,
    kg_in_stock: 20,
    color: "red",
    origin_country: "Turkey",
  },
  {
    name: "Bell Peppers",
    type: "vegetables",
    price_per_kg: 20.0,
    kg_in_stock: 30,
    color: "yellow",
    origin_country: "Spain",
  },
  {
    name: "Cauliflower",
    type: "vegetables",
    price_per_kg: 13.2,
    kg_in_stock: 22,
    color: "white",
    origin_country: "France",
  },
  {
    name: "Grapes",
    type: "fruits",
    price_per_kg: 28.0,
    kg_in_stock: 28,
    color: "purple",
    origin_country: "Italy",
  },
  {
    name: "Radishes",
    type: "vegetables",
    price_per_kg: 6.5,
    kg_in_stock: 35,
    color: "red",
    origin_country: "Germany",
  },
  {
    name: "Pineapples",
    type: "fruits",
    price_per_kg: 29.8,
    kg_in_stock: 17,
    color: "yellow",
    origin_country: "Philippines",
  },
  {
    name: "Kale",
    type: "greens",
    price_per_kg: 10.9,
    kg_in_stock: 40,
    color: "green",
    origin_country: "Canada",
  },
  {
    name: "Plums",
    type: "fruits",
    price_per_kg: 25.3,
    kg_in_stock: 24,
    color: "purple",
    origin_country: "Greece",
  },
  {
    name: "Artichokes",
    type: "vegetables",
    price_per_kg: 15.7,
    kg_in_stock: 12,
    color: "green",
    origin_country: "Spain",
  },
  {
    name: "Raspberries",
    type: "fruits",
    price_per_kg: 45.0,
    kg_in_stock: 10,
    color: "red",
    origin_country: "Chile",
  },

  {
    name: "Mushrooms",
    type: "vegetables",
    price_per_kg: 18.5,
    kg_in_stock: 28,
    color: "brown",
    origin_country: "USA",
  },
  {
    name: "Watermelons",
    type: "fruits",
    price_per_kg: 15.2,
    kg_in_stock: 15,
    color: "green",
    origin_country: "Brazil",
  },

  {
    name: "Blueberries",
    type: "fruits",
    price_per_kg: 38.6,
    kg_in_stock: 18,
    color: "blue",
    origin_country: "USA",
  },
  {
    name: "Cilantro",
    type: "greens",
    price_per_kg: 5.5,
    kg_in_stock: 25,
    color: "green",
    origin_country: "Mexico",
  },
];
