export const goods = [
  {
    name: "Cucumbers",
    type: "vegetables",
    price: 15.0,
    remained: 30,
    color: "green",
    country: "Poland",
  },
  {
    name: "Apples",
    type: "fruits",
    price: 18.8,
    remained: 40,
    color: "red",
    country: "Ukraine",
  },
  {
    name: "Potatoes",
    type: "vegetables",
    price: 8.5,
    remained: 60,
    color: "brown",
    country: "Ukraine",
  },
  {
    name: "Bananas",
    type: "fruits",
    price: 32.0,
    remained: 25,
    color: "yellow",
    country: "Ecuador",
  },
  {
    name: "Onions",
    type: "vegetables",
    price: 5.0,
    remained: 45,
    color: "white",
    country: "Ukraine",
  },
  {
    name: "Oranges",
    type: "fruits",
    price: 22.3,
    remained: 35,
    color: "orange",
    country: "Spain",
  },
  {
    name: "Carrots",
    type: "vegetables",
    price: 9.2,
    remained: 55,
    color: "orange",
    country: "Ukraine",
  },
  {
    name: "Pears",
    type: "fruits",
    price: 20.1,
    remained: 28,
    color: "yellow",
    country: "Ukraine",
  },
  {
    name: "Broccoli",
    type: "vegetables",
    price: 12.5,
    remained: 20,
    color: "green",
    country: "Poland",
  },
  {
    name: "Melons",
    type: "fruits",
    price: 28.7,
    remained: 18,
    color: "green",
    country: "Turkey",
  },
  {
    name: "Tomatoes",
    type: "vegetables",
    price: 14.3,
    remained: 42,
    color: "red",
    country: "Ukraine",
  },

  {
    name: "Asparagus",
    type: "vegetables",
    price: 18.0,
    remained: 15,
    color: "green",
    country: "Mexico",
  },
  {
    name: "Mangoes",
    type: "fruits",
    price: 25.6,
    remained: 32,
    color: "yellow",
    country: "India",
  },
  {
    name: "Lettuce",
    type: "greens",
    price: 6.8,
    remained: 38,
    color: "green",
    country: "Ukraine",
  },
  {
    name: "Peaches",
    type: "fruits",
    price: 23.4,
    remained: 26,
    color: "red",
    country: "Spain",
  },
  {
    name: "Peas",
    type: "vegetables",
    price: 11.2,
    remained: 48,
    color: "green",
    country: "Ukraine",
  },
  {
    name: "Avocado",
    type: "fruits",
    price: 34.9,
    remained: 24,
    color: "green",
    country: "Mexico",
  },
  {
    name: "Cabbage",
    type: "vegetables",
    price: 7.5,
    remained: 36,
    color: "white",
    country: "Ukraine",
  },
  {
    name: "Pumpkin",
    type: "vegetables",
    price: 7.3,
    remained: 86,
    color: "white",
    country: "Ukraine",
  },
  {
    name: "Spinach",
    type: "greens",
    price: 9.7,
    remained: 18,
    color: "green",
    country: "USA",
  },
  {
    name: "Strawberries",
    type: "fruits",
    price: 40.5,
    remained: 15,
    color: "red",
    country: "Mexico",
  },
  {
    name: "Zucchini",
    type: "vegetables",
    price: 14.8,
    remained: 25,
    color: "green",
    country: "Italy",
  },
  {
    name: "Cherries",
    type: "fruits",
    price: 35.2,
    remained: 20,
    color: "red",
    country: "Turkey",
  },
  {
    name: "Bell Peppers",
    type: "vegetables",
    price: 20.0,
    remained: 30,
    color: "yellow",
    country: "Spain",
  },
  {
    name: "Cauliflower",
    type: "vegetables",
    price: 13.2,
    remained: 22,
    color: "white",
    country: "France",
  },
  {
    name: "Grapes",
    type: "fruits",
    price: 28.0,
    remained: 28,
    color: "purple",
    country: "Italy",
  },
  {
    name: "Radishes",
    type: "vegetables",
    price: 6.5,
    remained: 35,
    color: "red",
    country: "Germany",
  },
  {
    name: "Pineapples",
    type: "fruits",
    price: 29.8,
    remained: 17,
    color: "yellow",
    country: "Philippines",
  },
  {
    name: "Kale",
    type: "greens",
    price: 10.9,
    remained: 40,
    color: "green",
    country: "Canada",
  },
  {
    name: "Plums",
    type: "fruits",
    price: 25.3,
    remained: 24,
    color: "purple",
    country: "Greece",
  },
  {
    name: "Artichokes",
    type: "vegetables",
    price: 15.7,
    remained: 12,
    color: "green",
    country: "Spain",
  },
  {
    name: "Raspberries",
    type: "fruits",
    price: 45.0,
    remained: 10,
    color: "red",
    country: "Chile",
  },

  {
    name: "Mushrooms",
    type: "vegetables",
    price: 18.5,
    remained: 28,
    color: "brown",
    country: "USA",
  },
  {
    name: "Watermelons",
    type: "fruits",
    price: 15.2,
    remained: 15,
    color: "green",
    country: "Brazil",
  },

  {
    name: "Blueberries",
    type: "fruits",
    price: 38.6,
    remained: 18,
    color: "blue",
    country: "USA",
  },
  {
    name: "Cilantro",
    type: "greens",
    price: 5.5,
    remained: 25,
    color: "green",
    country: "Mexico",
  },
];
